# Project Roadmap & Implementation Plan Reboot

With the core Lead Discovery, Data Enrichment, and CRM workflows fully operational (including event filtering, robust agents, and the revamped Lead Details layout), Spectral Soundworks is primed for its next phase. This plan outlines high-impact initiatives to evolve the platform from an internal lead discovery tool into a complete client management and collaboration suite.

## User Review Required

> [!IMPORTANT]  
> Please review the brainstormed initiatives below. Let me know which of these areas you'd like to prioritize next. We can focus on a single initiative or mix and match features.

## Open Questions

1. **Client Interaction**: Do you want to start inviting actual clients to the platform soon? If so, the Client Portal (Initiative 1) and Invoicing (Initiative 4) should be the priority.
2. **Lead Volume**: Are you managing enough leads now that a visual pipeline (Kanban board) would significantly improve your workflow?
3. **Outreach Automation**: Do you prefer to manually review and send all outreach, or would you like to explore deeper integrations (like Gmail API or Instagram scraping/automation) to send messages directly from the app?

---

## Brainstormed Initiatives

### Initiative 1: The Client Portal (Audio Collaboration & Feedback)
**Goal:** Activate the `Project`, `ProjectFile`, and `ProjectFeedback` models to create a seamless, client-facing experience.
- **Token-Based Access:** Clients receive a secure, magic link (`/portal/[token]`) to view their project without needing to create an account or log in.
- **Audio Player Integration:** Build a custom audio player for working files (e.g., mixdowns, masters).
- **Timestamped Feedback:** Allow clients to pause the track and drop comments at specific timestamps (utilizing the `timestamp` field in `ProjectFeedback`).
- **File Delivery:** Provide download links for final deliverable files once the project is marked complete or paid.

### Initiative 2: Lead Pipeline Visualization (Kanban Board)
**Goal:** Enhance the CRM experience by making lead management more visual and intuitive.
- **Drag-and-Drop Interface:** Build a Kanban-style board where columns represent `LeadStatus` (NEW, QUALIFIED, CONTACTED, FOLLOW_UP, WON, LOST).
- **Quick Actions:** Allow one-click actions from the board (e.g., log a note, schedule follow-up, or view social stats).
- **Stale Lead Indicators:** Visually highlight cards that have been in the `FOLLOW_UP` column for too long, integrating with our existing Follow-Up Reminder agent.

### Initiative 3: GenAI-Powered Outreach & Tone Matching
**Goal:** Make cold outreach highly personalized and efficient.
- **Contextual Draft Generation:** Feed the artist's recent Instagram captions, Spotify genres, and location into an LLM to generate highly specific, non-generic message drafts.
- **Tone Variations:** UI toggles to quickly switch the `MessageDraft` tone (e.g., "Casual", "Professional", "Fan-first").
- **Email/DM Integration:** Expand the `MessageDraft` UI to allow one-click copying, or direct sending if we integrate a mail provider (like Resend/SendGrid) or an Instagram DM deep-link (`ig://`).

### Initiative 4: Invoicing & Payments (Stripe Integration)
**Goal:** Monetize the workflow directly within Spectral Soundworks.
- **Invoice Generation:** Build an interface to create and manage `ProjectInvoice` records with line items, tax, and subtotals.
- **Stripe Checkout:** Integrate Stripe to generate payment links (`stripePaymentUrl`).
- **Auto-Unlock Deliverables:** Automatically transition project status and unlock `FileType.DELIVERABLE` files once the invoice is marked as paid via Stripe webhooks.

### Initiative 5: Analytics & Conversion Dashboard
**Goal:** Understand campaign performance and artist trends.
- **Funnel Metrics:** Visualize the conversion rate from NEW -> QUALIFIED -> WON.
- **Genre & Location Heatmaps:** Analyze which cities or genres yield the highest response rates.
- **Agent Activity Log:** A unified UI to view the logs generated by our background scripts (Lead Scoring, Stale Data Enrichment, etc.).

---

## Proposed Next Steps

Once you select a priority initiative (or a specific feature from the list above), I will break it down into a detailed, file-by-file execution plan in this document, detailing the specific components, API routes, and database changes required.
