- [x] Terminate all hanging Node.js processes
- [x] Restart PostgreSQL container
- [ ] Regenerate Prisma Client
- [ ] Verify database connectivity with scratch script
- [ ] Start Next.js development server
- [ ] Verify Leads page loads data in browser
- [ ] Verify Lead Discovery actors are operational
