
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.2
 * Query Engine version: 94a226be1cf2967af2541cca5529f0f7ba866919
 */
Prisma.prismaVersion = {
  client: "7.4.2",
  engine: "94a226be1cf2967af2541cca5529f0f7ba866919"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ArtistScalarFieldEnum = {
  id: 'id',
  name: 'name',
  instagramHandle: 'instagramHandle',
  instagramProfileUrl: 'instagramProfileUrl',
  instagramProfileImageUrl: 'instagramProfileImageUrl',
  spotifyArtistId: 'spotifyArtistId',
  spotifyArtistUrl: 'spotifyArtistUrl',
  spotifyImageUrl: 'spotifyImageUrl',
  spotifyAccent: 'spotifyAccent',
  spotifyAccentStrong: 'spotifyAccentStrong',
  spotifyHighlight: 'spotifyHighlight',
  officialSiteUrl: 'officialSiteUrl',
  location: 'location',
  city: 'city',
  state: 'state',
  country: 'country',
  genre: 'genre',
  tags: 'tags',
  bio: 'bio',
  emails: 'emails',
  followerCount: 'followerCount',
  lastPostAt: 'lastPostAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeadScalarFieldEnum = {
  id: 'id',
  artistId: 'artistId',
  status: 'status',
  score: 'score',
  scoreRationale: 'scoreRationale',
  lastContactedAt: 'lastContactedAt',
  nextActionAt: 'nextActionAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReleaseScalarFieldEnum = {
  id: 'id',
  artistId: 'artistId',
  spotifyTrackId: 'spotifyTrackId',
  spotifyReleaseId: 'spotifyReleaseId',
  title: 'title',
  releaseDate: 'releaseDate',
  imageUrl: 'imageUrl',
  url: 'url',
  releaseType: 'releaseType',
  createdAt: 'createdAt'
};

exports.Prisma.InstagramPostScalarFieldEnum = {
  id: 'id',
  artistId: 'artistId',
  instagramPostId: 'instagramPostId',
  caption: 'caption',
  imageUrl: 'imageUrl',
  postedAt: 'postedAt',
  url: 'url',
  createdAt: 'createdAt'
};

exports.Prisma.MessageDraftScalarFieldEnum = {
  id: 'id',
  leadId: 'leadId',
  tone: 'tone',
  body: 'body',
  source: 'source',
  selected: 'selected',
  createdAt: 'createdAt'
};

exports.Prisma.ActivityScalarFieldEnum = {
  id: 'id',
  leadId: 'leadId',
  type: 'type',
  note: 'note',
  occurredAt: 'occurredAt',
  createdAt: 'createdAt'
};

exports.Prisma.ProjectScalarFieldEnum = {
  id: 'id',
  artistId: 'artistId',
  title: 'title',
  portalToken: 'portalToken',
  status: 'status',
  rating: 'rating',
  review: 'review',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjectFileScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  name: 'name',
  url: 'url',
  key: 'key',
  size: 'size',
  mimeType: 'mimeType',
  type: 'type',
  isPublic: 'isPublic',
  createdAt: 'createdAt'
};

exports.Prisma.ProjectFeedbackScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  content: 'content',
  resolved: 'resolved',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.LeadStatus = exports.$Enums.LeadStatus = {
  NEW: 'NEW',
  QUALIFIED: 'QUALIFIED',
  CONTACTED: 'CONTACTED',
  FOLLOW_UP: 'FOLLOW_UP',
  WON: 'WON',
  LOST: 'LOST'
};

exports.ActivityType = exports.$Enums.ActivityType = {
  MESSAGE_SENT: 'MESSAGE_SENT',
  REPLY_RECEIVED: 'REPLY_RECEIVED',
  FOLLOW_UP_SET: 'FOLLOW_UP_SET',
  STATUS_CHANGE: 'STATUS_CHANGE',
  NOTE: 'NOTE'
};

exports.ProjectStatus = exports.$Enums.ProjectStatus = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED'
};

exports.FileType = exports.$Enums.FileType = {
  WORKING: 'WORKING',
  DELIVERABLE: 'DELIVERABLE'
};

exports.Prisma.ModelName = {
  Artist: 'Artist',
  Lead: 'Lead',
  Release: 'Release',
  InstagramPost: 'InstagramPost',
  MessageDraft: 'MessageDraft',
  Activity: 'Activity',
  Project: 'Project',
  ProjectFile: 'ProjectFile',
  ProjectFeedback: 'ProjectFeedback'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
